server:
  port: 8082
spring:
  h2:
    console:
      enabled: true
  graphql:
    schema:
      printer:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:memdb
    driverClassName: org.h2.Driver
    username: sa
    password: